### ISSUE TITLE
Speichern Buttons

### ISSUE THREAD

**Issue by 9teufel** [inspiredminds/contao-isotope-edit-order-addresses#1]
Ein Feature das ich schon lange vermisst habe (sollte eigentlich in den Isotope Core) - danke! 

Beim Bearbeiten sind die Buttons "Speichern und neu" und "Speichern und duplizieren" ohne Nutzen, bzw. für die Datenbank sogar kontraproduktiv. "Speichern und schließen" und "Speichern und zurück" haben das selbe Ziel, da würde auch ein Button reichen.

**Comment by fritzmg** [comment]
Done and released as `1.0.1`.
